### ISSUE TITLE
Repeatedly modifying Scope

### ISSUE THREAD

**Issue by markschl** [rhaiscript/rhai#348]
I'm very interested in using Rhai foremost (but not necessarily exclusively) as an expression evaluation engine, where a compiled AST is evaluated possibly millions of times. Before every execution, some global variables are changed.
Having looked at the documentation, all of this seems possible by compiling an AST and then repeatedly calling `Engine::eval_ast_with_scope()`. 

But what I see as a potentially major bottleneck is the fact, that modifying values using `Scope::set_value()` always implies looking up the variable by its name. I wonder, whether there would be a possibility to improve this, e.g. by allowing access to the internal `values` by index. However, I'm not familiar with the internals of Rhai, so I don't know, whether it can happen, that the index of a variable changes during expression evaluation?

Or maybe, my use case is not the intended use-case, I'm open to suggestions :) Thanks!

**Comment by schungx** [comment]
Rhai doesn't know what values you pushed into the scope when it compiles the script, so there is nothing it can do but to do a linear name search.

However, if your global variables are constants (mostly they are), you can consider a variables resolver: https://rhai.rs/book/engine/var.html

**Comment by schungx** [comment]
Now, some caveat.  Looking at your use case, you seem to care a lot about speed, if you're concerned even with searching within the `Scope`.  In that case, the AST-walking nature of Rhai is probably going to be slower than a simple name search through the `Scope`.

If you do not need all the flexibility of Rhai and just want a fast expressions engine, you can consider some other scripting language that compiles to bytecodes.  They will run much faster than Rhai.

**Comment by schungx** [comment]
> this would actually allow to define kind of a custom scope with any underlying data structure.

You're right.  Actually, there doesn't even need to be a custom scope.  `on_var` hijacks the variable access process and some users don't even have the data structure built at all - the values are read from a database etc.

**Comment by timfish** [comment]
We're using Rhai to perform maths and measurements on high sample-rate data from USB hardware. Without much performance tuning my desktop machine peaks at around 2.5GS/s throughput.

To do this we don't actually use Rhai to perform the calculations on every sample point. We having wrapping types/structs that contain blocks of data or iterators and then we override operators in Rhai. ALL the heavy computation happens in Rust.

**Comment by markschl** [comment]
Playing around a bit with Rhai and ExprTk, a [math-focused C++ engine](https://github.com/ArashPartow/exprtk), for which [I created bindings once](https://github.com/markschl/exprtk_rs), I found that Rhai was slower by around a factor of 100, so I'd have to see if it fits for my needs. ExprTk, although not compiling to bytecode, seems pretty focused on repeated evaluation speed, so this result is probably not very surprising. Maybe to explain, I was actually searching for ExprTk alternatives to be included in [this project](https://github.com/markschl/seqtool).

I noticed that the `'static`  lifetime requirement for the closure supplied to `on_var()` makes it not so easy to implement a custom scope. But as @schungx noted, AST evaluation in general may take more time than variable resolution, so I guess I would need a good reason if implementing a "custom" scope.

**Comment by schungx** [comment]
There are a few reasons why Rhai would be slower:

1) In Rhai, all operators are implemented as function calls that can be overloaded.  This flexibility means a function resolution step for each operator, and there are multiple layers of function spaces added on top of each other.

2) Rhai provides ruggedness by protecting against a lot of faults.  Use the `unchecked` feature and it'll be a bit faster.

3) If you use `no_closure`, then there is no sharing of variables and it'll again run a bit faster.  Check out https://rhai.rs/book/start/builds/performance.html

4) Rhai values are dynamic and they can represent any Rust type.  I believe ExprTk needs to be compiled for numbers only...  but I may be wrong.  Type inspection causes overheads.

5) Rhai allows you to overload functions, operators and syntax, which is not possible for a rigid language that optimizes on speed.

Nevertheless, I would expect an AST-walking interpreter to not be 100x faster than Rhai... since Rhai itself is roughly 5x slower than Python (which is bytecodes based).  Therefore, to be 100x faster than Rhai, it must be 20x faster than Python which is _very_ fast.  Even Wren is only about 2-3x faster than Python.

Are you sure your benchmarks are fair?

**Comment by schungx** [comment]
> I noticed that the `'static` lifetime requirement for the closure supplied to `on_var()` makes it not so easy to implement a custom scope

You can bypass the `'static` requirement by using interior mutability, at some locking costs.

In general, you'd consider `on_var` only when you have 1) a very large number of variables, 2) only a very small portion is ever used in each script, 3) which variables used by the script is not predictable, 4) you're running different scripts each time (obviously if you have the same script, you can simply detect the variables used).

**Comment by markschl** [comment]
Sorry, I didn't mean to post unfair benchmarks. I was essentially testing simple mathematical expressions such as "x + 2", at which ExprTk is very good (being highly optimized for that), they claim near-native speed on their homepage. So I think, you could say it's an unfair comparison, because Rhai has many more features than ExprTk.

Thanks for your hints!

**Comment by schungx** [comment]
Yes, I guess that's true because `x+y` is `$f00` which is one of the special functions.  It is then called directly into the native compiled function, which runs at native speed.  That's of course they need to know that both parameters are numbers, which I suppose they can tell at parsing time.

**Comment by timfish** [comment]
> I was essentially testing simple mathematical expressions such as "x + 2"

This is exactly how we're using Rhai, but in our case, `x` is a wrapping type which contains a clonable iterator over the raw data. 

We then overload `+` for our wrapping type:
```rust
#[rhai_fn(name = "+")]
pub fn add_int(a: OurWrappingIter, b: i64) -> OurWrappingIter {
    a.with_new_iter(AddIntIter::new(&a, b))
}
```
With this in place, evaluating `x + 2` in Rhai returns a `OurWrappingIter`. This is a chained iterator rather than a result. Rhai is only being used to chain up iterators for your calculation. To get the resulting data, you iterate over `OurWrappingIter` and the data is passed through the chain of iterators. To make the iterator chains fast, we use an enum rather than a trait so everything is statically dispatched.

**Comment by schungx** [comment]
In other words all your data are vectors?

Or are they more complicated data structures that are wrapped inside an iterator?

**Comment by timfish** [comment]
> Or are they more complicated data structures that are wrapped inside an iterator?

We have multiple data sources that implement the iterator in different ways. The data can come as a stream straight from a hardware device or from compressed blocks in a file, etc. The iterators usually hold `Arc`s of their underlying data so they're cheap to clone. 

All sources are eventually exposed as a kind of `ClonableExactSizeIterator<Item = f64>`. Our wrapper also has other metadata attached such as sample-rate and units so we can do things like `low_pass(A, 10000)` with an iterative convolution.

**Comment by schungx** [comment]
Ah.  Makes sense.

**Comment by timfish** [comment]
I did have an early version that used vector blocks rather than iterators. I expected it to be faster but I couldn't make it happen. There were loads of huge allocations and many things had to be designed specifically to work with the blocks. 

Iterators turned out to be a lot simpler and when I got it working via static dispatch they were also fast enough.

**Comment by schungx** [comment]
Is this issue resolved and can we close this?

**Comment by markschl** [comment]
Yes, thanks for your comments!
