### ISSUE TITLE
parsing u64 number literal failed

### ISSUE THREAD

**Issue by Xudong-Huang** [rhaiscript/rhai#427]
The following code would fail, because the default INT is i64.
```rust
let v = engine.eval::<i64>("0xfffffffffeff8ffc").expect("failed to parse INT") as u64;
```
Is it possible to parse such u64 literals? 
In my case, I need to assign u64 values to some kind of registers.

**Comment by schungx** [comment]
No, `INT` is always signed.  You may want to treat `INT` as a bit-field to set individual bits.

**Comment by Xudong-Huang** [comment]
Is it possible to have an API to set the default INT type, e.g. `engine.set_default_int::<u64>()`

**Comment by schungx** [comment]
It is possible, but probably at a huge cost to performance, as all math operations now have to check the type of the number instead of compiled in.

In fact, you _can_ use `u64` or all other integer types in Rhai.  They are all supported out of the box.

You can register your own `parse_u64` function that returns a `u64`, and then Bob's your uncle!

```rust
let x = parse_u64("0xfffffffffeff8ffc");
x.type_of()        // "u64"
```

**Comment by Xudong-Huang** [comment]
Thanks! I will implement my own parsing fn then.
