### ISSUE TITLE
How about an optional trailing semicolon?

### ISSUE THREAD

**Issue by RazrFalcon** [rhaiscript/rhai#473]
I understand that Rhai tries to mimic Rust, but what about an optional trailing semicolon? Just like in Swift.

Is is purely a design decision or is it hard to implement?

**Comment by schungx** [comment]
Rhai always take the _last_ statement's value as the return value of a block.  It doesn't matter whether the last statement terminates with a semicolon or not.  That's because Rhai has no types and so does not require the distinction as per Rust.

`{ foo }` and `{ foo; }` both return the same value.

**Comment by RazrFalcon** [comment]
I was talking about semicolons in general, not only in the return statement. I would really like to have the same logic as in Swift.

**Comment by schungx** [comment]
Not sure how Swift does it... do you mean terminate statement by line ending?

**Comment by schungx** [comment]
I just found https://forums.swift.org/t/what-are-the-rules-of-automatic-semicolon-insertion-in-swift/43532/12

Personally, I think this is more trouble than is worth...  Swift has to add more rules to parsing in order to be able to skip some semicolons...  I'd rather just keep those semicolons...

Not that it would be hard to implement - actually probably quite easy, but the additional parsing rules will be hairy as they skip through multiple statements, i.e. the second statement is not a statement if it is half of a binary operator which must have white-spaces around...

**Comment by RazrFalcon** [comment]
Hm... I see. I just thought maybe it was purely a stylistic choice. Personally, I think it makes code that easier to read. And I  do use Rust and Swift extensively, so I can compare. But I do agree that some rules are a bit weird.

Anyway, it's up to you. This is just a suggestion.

**Comment by schungx** [comment]
Closing this for now.
