### ISSUE TITLE
How to modify interpolated string

### ISSUE THREAD

**Issue by cn-kali-team** [rhaiscript/rhai#500]
rahi's original interpolated string is ${}, but this token is occupied in my text. I want to change it to {{}}.

I [tried](https://rhai.rs/book/engine/token-mapper.html) 
- code 
```
let target = "hi";
let s = `${target}/get`;
print(s);
```
- println!("{:?}", token);
```
Let
Identifier("target")
Equals
StringConstant("hi")
SemiColon
Let
Identifier("s")
Equals
InterpolatedString("")
LeftBrace
Identifier("target")
RightBrace
StringConstant("/get")
SemiColon
Reserved("print")
LeftParen
Identifier("s")
RightParen
SemiColon
EOF
```

---
- code 
```
let target = "hi";
let s = `{{target}}/get`;
print(s);
```
- token
```
Let
Identifier("target")
Equals
StringConstant("hi")
SemiColon
Let
Identifier("s")
Equals
StringConstant("{{target}}/get")
SemiColon
Reserved("print")
LeftParen
Identifier("s")
RightParen
SemiColon
EOF
{{target}}/get
```
- I can't find InterpolatedString

**Comment by schungx** [comment]
Since `` `{{target}}/get` `` contains no `${...}`, meaning that it is just a simple string, the tokenizer interprets it as a simple string constant, which is what you'd expect.

At this point, it is really not possible to change `${...}` into `{{...}}` for interpolated strings because the format is built into Rhai's tokenizer.

**Comment by cn-kali-team** [comment]
Thank you for your answer. I will try to solve this problem in other ways
