### ISSUE TITLE
Feature Request: Scope per Object

### ISSUE THREAD

**Issue by markusmoenig** [rhaiscript/rhai#553]
## Request

Allow objects to have their own scope. Making it possible to handle entities with their own set of variables efficiently.

For example

`engine.register_object_scope(name: "Target", scope: target_scope);`

Example script usage

`Target:HP -= 2` or `Target.HP -= 2`

## Reasoning

In games you often have entities or characters with their own variable sets. Currently, making an entity Target visible inside the scope of another entity Player would mean to:

* Create a custom struct with a custom indexer
* Copy all variables from Target to the custom struct
* Register the struct
* Run the script, address Target variables as `Target["HP"] -= 2`
* Copy all variables back from the custom indexer into the Scope of Target.

All of this is:

* Slow, especially when you break down scripts into a node system (see attached) with possible hundreds or thousands of expression and script calls per tick for a medium sized game.
* The `Target["HP"]` syntax is complicated and very "techy" especially for non-developers. Easy to make mistakes.

Allowing objects with scopes inside scripts would be efficient and introduce an easy syntax to modularize entities inside scripts.

Disclaimer: I do not know how much work this is (or if it is even possible) and have no idea if this is a reasonable request or not. Just requesting what I need.

Thanks

<img width="1352" alt="Screen Shot 2022-04-15 at 06 57 15" src="https://user-images.githubusercontent.com/10293923/163495591-9ae71b4d-0223-4fe9-8302-4988744270b5.png">
.

**Comment by schungx** [comment]
OK, it seems like what you want is _cross-linking_ or _cross-referencing_.  Rhai does not have references (it clones instead), therefore you have your problem.

The trick is usually to _avoid linking_ by passing in _addresses_ to your entity instead of a hard link.  For example, in your usage:

```rust
// Keep all entities in a single object map
// Notice that you can keep different TYPES of entities in the same map,
// so you don't have the restrictions of a typical ECS
let entities = #{ "me": Player::new(), "monster1": NPC::new("cute") , "weapon1": Weapon::LaserGun("me") };

const ME = "me";
let Target = "monster1";

// Map 'this' pointer to the entities set
fn fire_weapon(source, target, tool) {
    this[target].hp -= this[tool].damage;
    if this[target].hp < 0 {
        this[target].kill();
    }
    this[source].morale += 1;
}

entities.fire_weapon(ME, Target, "weapon1");
```

If you run snippets for different players, you can put the master `entities` map object into a custom `Scope` and simply make it available to all scripts.

Of course, that means you run the risk of exposing other players' data to each player in scripts.

BTW, there is already this warning in the Book:

![image](https://user-images.githubusercontent.com/661318/163506201-d727bb6b-7e4a-433a-a319-dec692c4e5fe.png)

However, it doesn't seem to prevent loads of people from trying to do exactly that!  ;-)

**Comment by markusmoenig** [comment]
OK, thanks :-(

Problem is, there is no byte-code "Rusty" scripting language and I don not like the syntax of Lua or JS. And the speed of Rhai is actually very much OK. So yes, I guess Rhai would be great for this (and my game engine runs at 4-5 ticks a second, it is not targeting 60 fps shooter games).

I also think the syntax of

`this[target].hp -= this[tool].damage;` is "easy to use" from the scripting side.

Oh well, guess I have to write my own scripting engine long term.

Thanks for the feedback and for the fixes!

**Comment by schungx** [comment]
I've just edited the example with some better modelling...

**Comment by schungx** [comment]
> Problem is, there is no byte-code "Rusty" scripting language

There is Rune: github.com/rune-rs

It is byte-codes based and is probably better suited for games.  Nevertheless, depends on how much flexibility you need in your language.

**Comment by schungx** [comment]
> I also don't think the syntax of `this[target].hp -= this[tool].damage;` is "easy to use" from the scripting side.

True.  However, you'd _always_ get this kind of restrictions when using Rust.  Think about what happens if `target` and `tool` refer to the _same_ entity.  A scripting language that exposes both as mutable references will have two mut's to the same data, violating Rust's ownership rules.

And once you go there, the scripting language won't really be "Rust-like" and you'd be able to get into data races, deadlocks, circular references etc.  Afterwards, you'd always lead to the same conclusion: you need a GC.  At that time, Lua would start to look seriously attractive.

**Comment by schungx** [comment]
But, looking at your usage, may I propose a different alternative.

1) Expose a hidden variable containing all entities (e.g. `__ENTITIES__`).

2) Allow your scripts to refer to certain macro-like identifiers (e.g. `$ME$`, `$TARGET$`)

3) Before you compile your scripts, globally replace `$ME$` and `$TARGET$` with `__ENTITIES__[ ... ]`

```rust
fn fire_weapon() {
    if $WEAPON$ <= 0 {
        throw "No ammo!!!";
    }
    $TARGET$.hp -= $WEAPON$.damage;
    $WEAPON$.ammo -= 1;
    if $TARGET$.hp <= 10 {
        $TARGET$.speed /= 2;
    }
    $ME$.morale += 1;
}

**Comment by markusmoenig** [comment]
Wow, thanks for all the suggestions and help. Sorry I do not want to come over as too negative, I really like Rhai and just want to make it happen somehow.

In my use case the Scopes are just super convenient as I can use them as a general purpose container from inside the scripts and inside the Rust code as well. So I probably want to stick with them.

But your suggestion for a pre-processor is good, guess maybe the first step would just be to map 

`Target.hp` to `Target["hp"]` and live with the custom struct / indexer performance hit for now and sort this out over time.

Not really a big fan of the rune-rs syntax and API, guess Lua is the best alternative. But will stick with Rhai for now.

> Actually, in Rust itself, you'd be writing it this way instead of Target.hp -= Weapon.damage where Target and Weapon are &mut to the same data set.

Yes ok, but that's a usage problem. Thats like saying division should not be allowed because the user can do `4 / 0` :).

**Comment by schungx** [comment]
Actually, I have been seriously thinking of a _macro_ feature for Rhai, as more than one user has asked for exactly the same thing in order to simply scripts.

However, for casual usage, a global text search-and-replace works just fine, as long as you pick syntax that is very unlikely to show up inside the content of a string itself.  So you'd probably not use `Target` (since you'd have trouble with `message = "Target is destroyed!"`).  You'd probably use something like `#Target`, `$Target`, etc.

I'll keep the macro feature in mind and see if there really is a significant need for it.

**Comment by schungx** [comment]
> Target.hp to Target["hp"] and live with the custom struct / indexer performance hit

Properties like `hp` (which should be an `INT`) is unlikely to cause a significant performance hit due to data cloning.  However, expressions such as

```rust
Target.hp += 2;
```

consists of three calls: 1) get current value by calling the getter, 2) run `+=` operator, 3) set value by calling the setter.

For critical path stuff, you may want do register helper API:

```rust
target.do_damage(2);
target.bump_hp(10);
```

This way, it is only one single function call and is just about as efficient as it can get.

**Comment by markusmoenig** [comment]
> Actually, I have been seriously thinking of a macro feature for Rhai, as more than one user has asked for exactly the same thing in order to simply scripts.

I wanted to ask about Macros too, as I have d2, d4, d6, d8, d10, d12, d14, d16, d18, d20 and d100 (dice throw) variables which I update with random numbers in the scope every time before I call a script. More efficient would be to do d(2), d(4) etc and compute the value on the fly, however that syntax would not be good for non developers. So having a macro which maps "d2" to "__random(2)" would be nice (and more efficient).

**Comment by markusmoenig** [comment]
And btw; is there a reason why Scopes are not serializable ? That would be so convenient.

**Comment by schungx** [comment]
This is a perfect use case for [variable resolvers](https://rhai.rs/book/engine/var.html).

> And btw; is there a reason why Scopes are not serializable ? That would be so convenient.

That is because the data inside a `Scope` may not be serializable (e.g. a custom type that does not implement `Serialize`).

**Comment by markusmoenig** [comment]
Missed the variable resolver stuff, super!! Thanks again.

**Comment by schungx** [comment]
> Missed the variable resolver stuff, super!! Thanks again.

With a variable resolver you can simply do `d??` where `??` refer to any number 0-99.  And a random calculated every single time.

**Comment by markusmoenig** [comment]
Guess we can close this ?
