### ISSUE TITLE
engine's private data

### ISSUE THREAD

**Issue by zhuchuanjing** [rhaiscript/rhai#563]
is there any way to store some engine's private data?
such as  engine.path = "my work path"
used in native func

**Comment by schungx** [comment]
Check out https://rhai.rs/book/engine/eval-context.html?highlight=tag

The tag in the `EvalContext` can hold anything, but only for the current run.

If you need a constant or something, it is simplest to store it in a `Scope`, except that you can't access it in a native function.  If you need to access a persistent state in native functions, use `EvalContext::tag`.

**Comment by zhuchuanjing** [comment]
yeah, I notice the tag.but I can't initialize it,
waiting for the set_tag API

**Comment by schungx** [comment]
If you can pull from https://github.com/schungx/rhai

you can try out `Engine::set_default_tag`...

**Comment by schungx** [comment]
@zhuchuanjing  have you tried out the new functionality?

**Comment by cortesi** [comment]
Hi there. I need this exact functionality for a project that I'm considering rhai for. At the moment, I'm looking at smuggling my state into native functions through an opaque entry in Scope, but this is pretty ugly. Is this API likely to make it into the next release, or are you waiting for more feedback?

**Comment by schungx** [comment]
Yes, this API will go into the next release.

In the meantime, you can pull from this master, which already contains it.

**Comment by cortesi** [comment]
It turns out that this API is not what I need - I need to be able to evaluate a rhai script with a context provided at the time of call. Ideally, this would mean paramerizing the engine with a State type, and then having a `run_with_state` function that passes the state through to the underlying native implementations. This would be too intrusive a change for rhai, I feel. I have come up with a solution where I (very carefully) poke my state into a thread local after extending its lifetime with some unsafe code, letting my native functions access the state, and then clean clean the global state up once my invocation function exits. This is ugly and imperfect, but it works, and it's let me proceed to an initial rhai integration.

**Comment by schungx** [comment]
Why can't you put the state into the tag?  You can just spawn a new Engine for each call and set the context into the tag before you run the script.

**Comment by cortesi** [comment]
The scripts in this case are keyboard bindings that are defined by users in the form of many (maybe at the extremes, hundreds) of small scripts, with a built-in API with hundreds of entries, and I want to avoid the cost of setting up an engine for each invocation. Looking at the design, I guess it's possible to retain the AST for each script and retain the configured modules containing native functions, but I'd still have to create the engine and re-register the modules for each invocation. 

Separately, it's not clear at first sight how I would pass my complex state object through the `rhai::Dynamic`.

**Comment by schungx** [comment]
Even if you use the same Engine for multiple script runs, I still can't understand why you can't call `set_default_tag` each time before you run the script?

**Comment by cortesi** [comment]
Here's some code that mimics the broad structure of my project.

```rust
use rhai::{Dynamic, Engine, EvalAltResult, Module, AST};

struct State {}

fn invoke(state: &mut State, engine: Engine, script: AST) -> Result<(), Box<EvalAltResult>> {
    // What goes here?
    // engine.set_default_tag(Dynamic::from(state));
    Ok(())
}

fn main() -> Result<(), Box<EvalAltResult>> {
    let mut engine = Engine::new();
    let mut m = Module::new();
    m.set_raw_fn(
        "func",
        rhai::FnNamespace::Internal,
        rhai::FnAccess::Public,
        &[],
        move |context, args| {
            /// Operations on mutable state go here. 
            println!("{:?}", context.tag());
            Ok(())
        },
    );
    engine.register_static_module("test", m.into());

    let ast = engine.compile(r#"print(test::foo)"#)?;
    let mut state = State {};
    invoke(&mut state, engine, ast)?;
    Ok(())
}
```

The question is what goes in that invoke function. I want to execute the AST with the context of a mutable reference to an opaque state object, and be able to recover that state object in the invocation. Any suggestions?

**Comment by schungx** [comment]
Simple.  Wrap the state object in `Rc` and then set it as the default tag.

Then just read the tag in your Rust function.

**Comment by cortesi** [comment]
The `main()` function in the example is artificial: it's not so simple to have an owned `State` object or `Rc` at the point where invoke is called. The obvious choices here (say, making my State cloneable) are all worse than my hacky hack for smuggling state in, due to the nature of my project. 

A truly ergonomic API for my use case would be to parameterise Engine with a State type, then allow a mutable reference to be passed into native functions. It might have been worthwhile to do it like this from scratch, but I  don't think retrofitting this strategy onto rhai is worthwhile, though. The state issue is less of a concern at the moment in my testing of rhai than being able to check for invocations of non-existent functions in modules at compile time.

**Comment by schungx** [comment]
Yes, such retrofitting is troublesome at this point.

Do you require the state to be mutable?  If so, I'm afraid wrapping in `Rc<RefCell<State>>` is probably the only option you have.  Essentially, what you have in the state is a singleton, and a mutable singleton.   You really can't avoid `Rc` in this case.

**Comment by cortesi** [comment]
Yes, state must be mutable - the native functions are hooks that operate on the state by mutating it. The project is a new terminal UI library, and I'm hoping that rhai can handle keybindings, mouse bindings and macros/scripting. The "state" here is the entire widget tree and a global state object that tracks various internals of the app. 

And I agree that because of lifetime constraints on references, I'm constrained to some form of singleton, however you phrase it in the code. Ultimately, I can restrict the lifetime of this singleton to the duration of a script invocation and place it in a thread local, and the 2 lines of unsafe code I've landed on is probably the most flexible way to get this done without huge changes to cater for rhai in the rest of my codebase. I'm not unhappy with how that's ended up.

**Comment by schungx** [comment]
Yes, ultimately a singleton is what you need, especially later on if you'll be running multiple scripts simultaneously.

Your trick of using a thread-local variable to store a shared state is interesting...  If you can mock up a minimal example, I can put that in the Book as a usage pattern!
