### ISSUE TITLE
Is it possible to use "goto" in rhai?

### ISSUE THREAD

**Issue by youngzhaozju** [rhaiscript/rhai#569]
Hey,
I found the "goto" is a reserved keyword in rhai. 
https://rhai.rs/book/appendix/keywords.html?highlight=goto#reserved-keywords
So, is it possible to utilize it? I cannot find any example to handle goto logic. 
Thank you!
Regards,
Yang

**Comment by schungx** [comment]
It is reserved but not used at the moment...

Any particular reason you need `goto`?  Usually you can simulate it with exceptions.

**Comment by youngzhaozju** [comment]
> It is reserved but not used at the moment...
> 
> Any particular reason you need `goto`? Usually you can simulate it with exceptions.

Thank you for your kind reply!

I plan to develop a flow-chart-based programming tool based on rhai. Here is an example of the flow chart, https://www.edrawsoft.com/lunch-sunday-flowchart-example.html

I want to generate rhai script code based on the flow chart, and then run the logic using rhai. If the "goto" is available in rhai, the logic "Enjoy your lunch" in the flow chart will be very easy. Without the goto, I cannot find anyother way to do so.

Best regards,
Yang

**Comment by schungx** [comment]
Well, you always have to be careful where you're jumping to via `goto`.  For example, obviously you can jump back into a parent scope up the chain, but it would be difficult to jump into a separate inner scope without going through the chain of statements leading to that scope.

Now according to your lunch example, `Enjoy your lunch` needs to _escape_ out of any scope it is in.  That is the perfect case to throw a custom exception (which gets you out of any scope), or a simple `return` statement (which also gets you out of any functional scope).

Of course, to use `return` the statement must be inside a function; if you don't have a function, then you can use `throw` to throw a custom exception, that you can `catch` on the outside.

**Comment by schungx** [comment]
More illustration ,using your flow chart as an example.

![](https://www.edrawsoft.com/template/lunch-on-sunday-flowchart.png)

I suppose you're compiling each decision block in the chart as an `if` statement, which turns the chart into a structured nested block of statements.

If `Enjoy your lunch` breaks out of the entire thing, then you can simply wrap the whole code inside a `try` block and then throw a custom exception, finally `catch` it.

If you want to link two blocks, say, from `Anything you want to eat` back to `Find a restaurant`, then you have created a loop, and it must be compiled into Rhai as a loop.

If you want to link two blocks that are in separate branches, say, from `Order take out` to `Find a restaurant`, then you're in trouble, because you are jumping from one inner scope to another inner scope without going through the parent.

Obviously, one solution is to compile the whole thing into a state machine, looping and `switch`-ing on the state.  Then you can do anything you want with the graph.

**Comment by youngzhaozju** [comment]
> More illustration ,using your flow chart as an example.
> 
> ![](https://camo.githubusercontent.com/bc6ccb4c015154cf118028a6aadac215a6e18961fa1d4746ae2d33438dac8adb/68747470733a2f2f7777772e6564726177736f66742e636f6d2f74656d706c6174652f6c756e63682d6f6e2d73756e6461792d666c6f7763686172742e706e67)
> 
> I suppose you're compiling each decision block in the chart as an `if` statement, which turns the chart into a structured nested block of statements.
> 
> If `Enjoy your lunch` breaks out of the entire thing, then you can simply wrap the whole code inside a `try` block and then throw a custom exception, finally `catch` it.
> 
> If you want to link two blocks, say, from `Anything you want to eat` back to `Find a restaurant`, then you have created a loop, and it must be compiled into Rhai as a loop.
> 
> If you want to link two blocks that are in separate branches, say, from `Order take out` to `Find a restaurant`, then you're in trouble, because you are jumping from one inner scope to another inner scope without going through the parent.
> 
> Obviously, one solution is to compile the whole thing into a state machine, looping and `switch`-ing on the state. Then you can do anything you want with the graph.

Hey schungx,
Thanks so much for your kind reply! You inspired me a lot. I am trying to think about state machine and work flow engine instead of goto. Thank you again!
Best regards,
Yang

**Comment by schungx** [comment]
> Thanks so much for your kind reply! You inspired me a lot. I am trying to think about state machine and work flow engine instead of goto. Thank you again!

A state machine is perfect for encoding a flow graph because that's what a state machine is defined as: a number of states (blocks) with transitions (arrows) based on decisions.

You don't really need Rhai to run your flow chart (unless of course you need scripting for individual blocks).  You only need a simple states transition table and the machine should run itself.  It is dead simple to compile.
