### ISSUE TITLE
Shared Map doesn't work

### ISSUE THREAD

**Issue by AlexPublicProfile** [rhaiscript/rhai#573]
```rust
let m = Dynamic::from(my_map).into_shared();
engine.register_fn("my_fn", move || m.clone());
```
```rust
print(my_fn()); //prints my map
let m = my_fn(); //m - not shared map
print(m.my_key); //prints my_key value from my_map
print(my_fn().my_key); //error: 'Indexer not registered: map [string] (line 4, position 13)'
```
If you remove **.into_shared()** from the Rust code, then no errors occur.

**Comment by schungx** [comment]
The value of a function call is always a concrete value, never a shared value.  Therefore, your shared map is copied (i.e flattened) when it is returned from the function.  This is to avoid cycles such as putting a shared version of an array into itself.

As for the error, I think I'm missing a check somewhere for chained property calls.

**Comment by schungx** [comment]
I have tracked down the bug, and it'll be fixed in the next release.  Thanks for catching this.

BTW, it is no necessary for your map to be shared, as a function call always returns a concrete value which is a cloned copy.  Therefore, you can simply move your map into the closure and calling `clone` will clone it.

The bug you raised only occurs in this situation `func(...).prop` or `func(...)[idx]` where `func(...)` returns a clone of a shared value.
