### ISSUE TITLE
Massive slowdown on IntelliJ if macro expansion is enabled (and possibly rust-analyzer)

### ISSUE THREAD

**Issue by msparkles** [rhaiscript/rhai#737]
It would seem that, if possible, the best course of action is to exclude codegen from rust-analyzer.

It's not tested if pure R-A is slowed down by the macros, but at least according to IntelliJ:
> However, IntelliJ Rust shares some code for procedural macros expansion with [rust-analyzer](https://github.com/rust-analyzer/rust-analyzer).

It would seem that they're at least borrowing code for macro expansion from R-A.

Disabling macro expansion messes up other things, such as Copy not being considered when it's derived, and IntelliJ would promptly go on and complain about unable to move.

Indexing is significantly slower after the inclusion of Rhai in the project. We really hope there's a solution or at least a patch.

**Comment by schungx** [comment]
Well, I don't use IntelliJ so I can't really tell, but I use VScode with rust-analyzer and it is reasonably fast...

I suspect it has to do with certain settings?  What kind of speed drop do you observe?

**Comment by Mg138** [comment]
Mostly speed drop when pasting a block of code and waiting for the IDE to gather the context, as well as when searching for methods.

The only setting that seems to affect it is macro expansion, which propagates macro results and lets the IDE consider their results when parsing the code. (e.g. Copy won't be detected and IDEA would complain about moved values if the setting is disabled)

Are you using an SSD? It might be because our project is on an HDD, just maybe.

**Comment by schungx** [comment]
> Are you using an SSD? It might be because our project is on an HDD, just maybe.

True, I'm using VScode + rust-analyzer on a Surface laptop with SSD...

Nevertheless, much of the standard library is built with macros... so it is kinda difficult to turn it off and have Rhai work reasonably the same...

**Comment by schungx** [comment]
Closing for now.  Feel free to reopen if you have any more questions.
