### ISSUE TITLE
UNSIGNED_INT is private

### ISSUE THREAD

**Issue by Mg138** [rhaiscript/rhai#740]
Currently we have a problem with switch.

We used a workaround to make this a more-or-less working literal in Rhai:

```
switch target.as_neighbor() {
   "TOP_RIGHT" => TileCoord::RIGHT,
   "RIGHT" => TileCoord::BOTTOM_RIGHT,
   "BOTTOM_RIGHT" => TileCoord::BOTTOM_LEFT,
   "BOTTOM_LEFT" => TileCoord::LEFT,
   "LEFT" => TileCoord::TOP_LEFT,
   "TOP_LEFT" => TileCoord::TOP_RIGHT,
}
```

(In Rust..)
```rs
.register_fn("as_neighbor", |v: TileCoord| match v {
    TileCoord::TOP_RIGHT => Dynamic::from_str("TOP_RIGHT").unwrap(),
    TileCoord::RIGHT => Dynamic::from_str("RIGHT").unwrap(),
    TileCoord::BOTTOM_RIGHT => Dynamic::from_str("BOTTOM_RIGHT").unwrap(),
    TileCoord::BOTTOM_LEFT => Dynamic::from_str("BOTTOM_LEFT").unwrap(),
    TileCoord::LEFT => Dynamic::from_str("LEFT").unwrap(),
    TileCoord::TOP_LEFT => Dynamic::from_str("TOP_LEFT").unwrap(),
    _ => Dynamic::UNIT,
})
```

TileCoord is a hexagonal coordinate, all possible values of it represent a unique coordinate and it implements Hash as well.

Is it possible to add constants of such type as literals?

**Comment by schungx** [comment]
Enums are treated as opaque custom types so unlikely they would have literal support in the language.

On the other hand, it seems that you'd need `as_neighbour` anyway... Otherwise how can you read the field in a script?  Rhai doesn't have knowledge of enum variants. Therefore, usually the best way is to convert enum variants into strings or numbers.

In actual use cases, you probably access the enum field as string or numbers anyway.  So it is really not restricted to the `switch` statement.

Unless your enum field is never needed in script, only to be passed as parameters into functions. Otherwise, if you ever want to inspect the value of that field in script, you'd need a data type that is easy to work with in script.

**Comment by Mg138** [comment]
They're not enums, TileCoord::TOP_RIGHT is just a constant, TileCoord is a struct of 3 i32's.

**Comment by Mg138** [comment]
We suppose we could make them into rhai Array's, but then we bumped into the problem of.. doing arithmetic with said arrays.

**Comment by schungx** [comment]
If the constants are combo types, not primitive types, then yes, it would not be possible to express that as a Rhai literal.

And three `i32`'s won't ever fit inside a single `Dynamic` anyway, so you're going to have to live with allocations.

I suggest you investigate whether your coordinates can fit into 16-bit?

**Comment by Mg138** [comment]
We can actually just fit the coord into 2 i32's and calculate the third component on the fly. (This is a quirk with the hexagonal coordinate system, the third component is more or less a convenient in calculations.)

I suppose there could exist a `Pair` type? One that has all the arithmetic implemented and acts like a strictly 2-sized rhai Array-- I can see it being useful in some cases, but it might not be as useful as most other things... And implementing it might be a bit harder than on paper.

Maybe we could take a crack at this if it's possible on paper? :eyes:

**Comment by schungx** [comment]
In that case, I would suggest just fitting it all inside an `i64`.  Define three properties on `i64`, say `x`, `y` and `z` that'll return the relevant number.

It is worth doing the calculation every time to get `z` in order to avoid allocations altogether.  That would make it very fast as the script is always just manipulating integers.

The `switch` statement would still be a problem though...  you'd need to have those constants as numbers, as you can't use constants in a `switch` statement.

**Comment by Mg138** [comment]
Hmm.

It's rather weird having magic numbers like that in the scripts, as they're roughly meant to be a reference for modders of our game... And also just, generally not wanting to have something cryptic like that.

We'll do the i64 thing and pack it into one integer, though.

**Comment by schungx** [comment]
Well, actually it is not that bad.  Say, you can have:

```rust
let coord = TileCoord::new(123, 456);

coord.x *= 2;
coord.y = -coord.z;
coord.z = coord.x;

switch coord {
    0xffffffff_00000000 => ...    // top-left?
}
```

**Comment by Mg138** [comment]
We just went with an if-else chain for now. Thanks for the suggestion of packing them into one integer, though!

**Comment by Mg138** [comment]
Actually we take that back, we remembered that rotating a hexagonal coordinate is very trivial :sweat:

No need to match anything really.

**Comment by Mg138** [comment]
Okay, new problem: we actually need the integer to be unsigned, or else arithmetic would be totally wrong.

But we can't access UNSIGNED_INT from Rhai.

**Comment by Mg138** [comment]
...Actually... unsigned doesn't solve the problem, oops.

2's complement is annoyingly frying my brain.

**Comment by Mg138** [comment]
Oh it's an error in our conversion code, never mind.
