### ISSUE TITLE
Feature: syntax `str[range]` support like rust string indexing by range

### ISSUE THREAD

**Issue by zitsen** [rhaiscript/rhai#841]
Expect:

```rust
let s = "abcd";
let n = s[1..3];
```

Now it reports:

```text
2: let n = s[1..3];
             ^ Data type incorrect: core::ops::range::Range<i64> (expecting i64)
```

Would this feature could be supported? Maybe I can contribute if you don't mind to add this, and give me some help to start.

**Comment by schungx** [comment]
Well, there is `sub_string` that does something similar...

The actual implementation may be quite involved, since indexer for strings cannot be overridden.  It is built-in.  Internally it uses mutable references to do its magic.  For example, if we implement this correctly for strings, you can do this:

```rust
let s = "abcdefg";
s[1..3] = "xyz";    // you can even modify a sub-range inside a string!
print(s);    // prints `axyzdefg`
```

**Comment by schungx** [comment]
You may look into the `Target` type to see how character indexing is done, and then adapt it to ranges if you want a shot at it?

**Comment by zitsen** [comment]
May you have time to review the pr: #845 ?

**Comment by schungx** [comment]
Will do that tomorrow

**Comment by schungx** [comment]
There are a few odds and ends that you missed, which I'll fix and update with a new drop.
